name: Build Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v5
        with:
          key: bun-install-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          path: ~/.bun/install/cache
      - run: bun install
      - run: bun run build

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v5
        with:
          key: bun-install-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          path: ~/.bun/install/cache
      - run: bun install
      - run: bun turbo run typecheck
